<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var common\models\Shop $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="shop-form">

    <?php $form = ActiveForm::begin([
    'id' => 'Shop',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute firm_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'firm_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(common\models\Firm::find()->all(), 'id', 'name'),
    [
        'prompt' => 'Select',
        'disabled' => (isset($relAttributes) && isset($relAttributes['firm_id'])),
    ]
); ?>

<!-- attribute workshop -->
			<?= $form->field($model, 'workshop')->textInput() ?>

<!-- attribute master_choice -->
			<?= $form->field($model, 'master_choice')->textInput() ?>

<!-- attribute minus_zp -->
			<?= $form->field($model, 'minus_zp')->textInput() ?>

<!-- attribute his_clients -->
			<?= $form->field($model, 'his_clients')->textInput() ?>

<!-- attribute sms -->
			<?= $form->field($model, 'sms')->textInput() ?>

<!-- attribute active -->
			<?= $form->field($model, 'active')->textInput() ?>

<!-- attribute ticket_type -->
			<?= $form->field($model, 'ticket_type')->textInput() ?>

<!-- attribute hurry -->
			<?= $form->field($model, 'hurry')->textInput() ?>

<!-- attribute discount -->
			<?= $form->field($model, 'discount')->textInput() ?>

<!-- attribute complex -->
			<?= $form->field($model, 'complex')->textInput() ?>

<!-- attribute workshop_choice -->
			<?= $form->field($model, 'workshop_choice')->textInput() ?>

<!-- attribute defect -->
			<?= $form->field($model, 'defect')->textInput() ?>

<!-- attribute deleted -->
			<?= $form->field($model, 'deleted')->textInput() ?>

<!-- attribute phone -->
			<?= $form->field($model, 'phone')->textarea(['rows' => 6]) ?>

<!-- attribute address -->
			<?= $form->field($model, 'address')->textarea(['rows' => 6]) ?>

<!-- attribute ispolnitel -->
			<?= $form->field($model, 'ispolnitel')->textarea(['rows' => 6]) ?>

<!-- attribute logo -->
			<?= $form->field($model, 'logo')->textarea(['rows' => 6]) ?>

<!-- attribute name -->
			<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!-- attribute firm_name -->
			<?= $form->field($model, 'firm_name')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('app', 'Shop'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

