<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var common\models\Service $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="service-form content">

    <?php $form = ActiveForm::begin([
            'id' => 'Service',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger'
        ]
    );
    ?>
    <hr>

    <div class="clearfix">
        <div class="col-sm-6">
            <!-- attribute category_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'category_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\ServiceCategory::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['category_id'])),
                ]
            ); ?>

            <!-- attribute name -->
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <!-- attribute base_cost -->
            <?= $form->field($model, 'base_cost')->textInput(['maxlength' => true]) ?>

            <!-- attribute fixed -->
            <?= $form->field($model, 'fixed')->checkbox() ?>

            <!-- attribute discount -->
            <?= $form->field($model, 'discount')->checkbox() ?>

            <!-- attribute margin -->
            <?= $form->field($model, 'margin')->textInput() ?>

            <!-- attribute comment -->
            <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>

        </div>
        <div class="col-sm-6">
            <!-- attribute barcode -->
            <?= $form->field($model, 'barcode')->textInput(['maxlength' => true]) ?>

            <!-- attribute unit -->
            <?= $form->field($model, 'unit')->textInput(['maxlength' => true]) ?>

            <!-- attribute time -->
            <?= $form->field($model, 'time')->textInput() ?>

            <!-- attribute ticket -->
            <?= $form->field($model, 'ticket')->textInput() ?>

            <!-- attribute hint -->
            <?= $form->field($model, 'hint')->textInput(['maxlength' => true]) ?>

            <!-- attribute payment -->
            <?= $form->field($model, 'payment')->textInput(['maxlength' => true]) ?>

        </div>
    </div>

    <hr/>

    <?php echo $form->errorSummary($model); ?>

    <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
            'id' => 'save-' . $model->formName(),
            'class' => 'btn btn-success'
        ]
    );
    ?>

    <?php ActiveForm::end(); ?>


</div>

