<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var common\models\Service $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="service-form">

    <?php $form = ActiveForm::begin([
            'id' => 'Service',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger'
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


            <!-- attribute category_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'category_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\ServiceCategory::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['category_id'])),
                ]
            ); ?>

            <!-- attribute base_cost -->
            <?= $form->field($model, 'base_cost')->textInput(['maxlength' => true]) ?>

            <!-- attribute time -->
            <?= $form->field($model, 'time')->textInput() ?>

            <!-- attribute ticket -->
            <?= $form->field($model, 'ticket')->textInput() ?>

            <!-- attribute num -->
            <?= $form->field($model, 'num')->textInput() ?>

            <!-- attribute fixed -->
            <?= $form->field($model, 'fixed')->textInput() ?>

            <!-- attribute margin -->
            <?= $form->field($model, 'margin')->textInput() ?>

            <!-- attribute discount -->
            <?= $form->field($model, 'discount')->textInput() ?>

            <!-- attribute payment -->
            <?= $form->field($model, 'payment')->textInput(['maxlength' => true]) ?>

            <!-- attribute deleted -->
            <?= $form->field($model, 'deleted')->textInput() ?>

            <!-- attribute comment -->
            <?= $form->field($model, 'comment')->textarea(['rows' => 6]) ?>

            <!-- attribute name -->
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <!-- attribute barcode -->
            <?= $form->field($model, 'barcode')->textInput(['maxlength' => true]) ?>

            <!-- attribute unit -->
            <?= $form->field($model, 'unit')->textInput(['maxlength' => true]) ?>

            <!-- attribute hint -->
            <?= $form->field($model, 'hint')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label' => Yii::t('app', 'Service'),
                        'content' => $this->blocks['main'],
                        'active' => true,
                    ],
                ]
            ]
        );
        ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
            ($model->isNewRecord ? 'Create' : 'Save'),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

