<?php

namespace frontend\components;

use yii\base\Component;
use Yii;

class Shop extends Component
{
    private $attribute = 'shop_id';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!is_null(Yii::$app->user->identity) && is_null(Yii::$app->session->get($this->attribute, null)))
            $this->set();
        //Yii::$app->session->get($this->attribute, 0);
    }

    public function get()
    {
        return Yii::$app->session->get($this->attribute);
    }

    public function set($shop_id = null)
    {
        if (is_null($shop_id)) {
            $shop_id = Yii::$app->user->identity->findAnyFirmShop();
        }
        //$this->attribute = $attribute;
        Yii::$app->session->set($this->attribute, $shop_id);
    }
}