<?php

namespace frontend\components;

use yii\base\Component;
use Yii;

class Shop extends Component
{
    private $attribute = 'shop_id';
    /**
     * @access private
     * @var $shop \common\models\Shop
     */
    private $shop = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //if (!is_null(Yii::$app->user->identity) && is_null(Yii::$app->session->get($this->attribute, null)))
        $this->set();
        //Yii::$app->session->get($this->attribute, 0);
    }

    public function get()
    {
        return Yii::$app->session->get($this->attribute);
    }

    public function getInstance()
    {
        return $this->shop;
    }

    public function getName()
    {
        return (is_null($this->shop)) ? "< Точка не выбрана >" : $this->shop->name;
    }

    public function set($shop_id = null)
    {
        if (is_null($shop_id)) {
            $this->shop = Yii::$app->user->identity->findAnyFirmShop();
            $shop_id = $this->shop->id;
        }
        //$this->attribute = $attribute;
        Yii::$app->session->set($this->attribute, $shop_id);
    }
}