<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "defect".
 *
 * @property integer $id
 * @property integer $pid
 * @property integer $firm_id
 * @property string $name
 * @property string $picture
 * @property integer $multi_select
 * @property integer $deleted
 *
 * @property \common\models\Firm $firm
 * @property \common\models\ServiceCategory[] $serviceCategories
 * @property string $aliasModel
 */
abstract class Defect extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'defect';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pid', 'firm_id', 'multi_select', 'deleted'], 'integer'],
            [['picture'], 'string'],
            [['name'], 'string', 'max' => 50],
            [['firm_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Firm::className(), 'targetAttribute' => ['firm_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pid' => 'родительская категория',
            'firm_id' => 'какой фирме',
            'name' => 'наименование',
            'picture' => 'назв. файла с картинкой',
            'multi_select' => 'мультиселект',
            'deleted' => 'удален',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFirm()
    {
        return $this->hasOne(\common\models\Firm::className(), ['id' => 'firm_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServiceCategories()
    {
        return $this->hasMany(\common\models\ServiceCategory::className(), ['defect_id' => 'id']);
    }


    /**
     * @inheritdoc
     * @return \common\models\query\DefectQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\DefectQuery(get_called_class());
    }


}
