<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "firm".
 *
 * @property integer $id
 * @property string $name
 * @property integer $deleted
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class Firm extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%firm}}';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['deleted'], 'integer'],
            [['name'], 'string', 'max' => 150]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Наименование',
            'created_at' => 'время создания',
            'deleted' => 'Активность',
        ];
    }
    
    /**
     * @inheritdoc
     * @return \common\models\query\FirmQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\FirmQuery(get_called_class());
    }


}
