<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "service_var".
 *
 * @property integer $id
 * @property integer $service_id
 * @property integer $pid
 * @property string $name
 * @property integer $add_cost
 * @property integer $multi_select
 *
 * @property \common\models\Service $service
 * @property string $aliasModel
 */
abstract class ServiceVar extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'service_var';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['service_id', 'pid', 'add_cost', 'multi_select'], 'integer'],
            [['name'], 'string', 'max' => 64],
            [['service_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Service::className(), 'targetAttribute' => ['service_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'service_id' => 'id услуги',
            'pid' => 'родительская категория',
            'name' => 'название',
            'add_cost' => 'прибавка к стоимости',
            'multi_select' => 'мультиселект',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getService()
    {
        return $this->hasOne(\common\models\Service::className(), ['id' => 'service_id']);
    }


    /**
     * @inheritdoc
     * @return \common\models\query\ServiceVarQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ServiceVarQuery(get_called_class());
    }


}
