<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var common\models\ServiceCategory $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="service-category-form">

    <?php $form = ActiveForm::begin([
            'id' => 'ServiceCategory',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger'
        ]
    );
    ?>

    <div class="">
        <p>
            <!-- attribute pid -->
            <?= $form->field($model, 'pid')->textInput() ?>

            <!-- attribute firm_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'firm_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\Firm::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['firm_id'])),
                ]
            ); ?>

            <!-- attribute shop_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'shop_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(common\models\Shop::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['shop_id'])),
                ]
            ); ?>

            <!-- attribute num -->
            <?= $form->field($model, 'num')->textInput() ?>

            <!-- attribute nalog_type -->
            <?= $form->field($model, 'nalog_type')->textInput() ?>

            <!-- attribute del -->
            <?= $form->field($model, 'del')->textInput() ?>

            <!-- attribute active -->
            <?= $form->field($model, 'active')->textInput() ?>

            <!-- attribute picture -->
            <?= $form->field($model, 'picture')->textarea(['rows' => 6]) ?>

            <!-- attribute name -->
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </p>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <div class="modal-footer">
            <div class="pull-left">
                <?= Html::button(
                    'Отмена',
                    ['class' => 'btn btn-default','data-dismiss'=>'modal']) ?>
            </div>

            <div class="pull-right">
                <?= Html::submitButton(
                    '<span class="glyphicon glyphicon-check"></span> ' . ($model->isNewRecord ? 'Create' : 'Save'),
                    [
                        'id' => 'save-' . $model->formName(),
                        'class' => 'btn btn-success'
                    ]
                );
                ?>
            </div>
        </div>



        <?php ActiveForm::end(); ?>

    </div>

</div>

